CREATE TABLE IF NOT EXISTS solicitudes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hero VARCHAR(60) NOT NULL,
    nombre VARCHAR(60) NOT NULL,
    email VARCHAR(100) NOT NULL,
    motivo TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);